### ISSUE TITLE
commands.py _read_sync calls to async method

### ISSUE THREAD

**Issue by josegomezr** [mogui/pyorient#110]
in Line 210 of [commands.py](https://github.com/mogui/pyorient/blob/master/pyorient/messages/commands.py#L210)

```python
# async-result-type can be:
# 0: no records remain to be fetched
# 1: a record is returned as a result set
# 2: a record is returned as pre-fetched to be loaded in client's
#       cache only. It's not part of the result set but the client
#       knows that it's available for later access
cached_results = self._read_async_records()
# cache = cached_results['cached']
```
Strangely this line never give me an error until now, somehow that call gives me an error.

```
Query: "SELECT *, idea.exclude('@type') FROM V WHERE @class = 'V' AND any().toLowerCase() LIKE '%comp%'"

Traceback (most recent call last):
  File "/home/asistente04/piggy/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/asistente04/piggy/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/asistente04/piggy/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/asistente04/piggy/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/asistente04/piggy/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/asistente04/piggy/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/asistente04/piggy/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/asistente04/piggy/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/asistente04/piggy/app/netdb.py", line 60, in queryResolver
    raw = db.query(sql)
  File "/home/asistente04/piggy/app/api/database.py", line 77, in query
    return self.client.query(*args);
  File "/home/asistente04/piggy/lib/python2.7/site-packages/pyorient/orient.py", line 261, in query
    .prepare(( QUERY_SYNC, ) + args).send().fetch_response()
  File "/home/asistente04/piggy/lib/python2.7/site-packages/pyorient/messages/commands.py", line 151, in fetch_response
    return self._read_sync()
  File "/home/asistente04/piggy/lib/python2.7/site-packages/pyorient/messages/commands.py", line 210, in _read_sync
    cached_results = self._read_async_records()
  File "/home/asistente04/piggy/lib/python2.7/site-packages/pyorient/messages/base.py", line 416, in _read_async_records
    str(self._callback) + " is not a callable function", [])
PyOrientBadMethodCallException: None is not a callable function
```

I've just commented it and the error its gone, but don't know what consequences does that change will imply.

**Comment by Ostico** [comment]
Hi @josegomezr 

can you post a little snippet of your code?

Thanks

**Comment by josegomezr** [comment]
Here is the [Full Snippet](https://gist.github.com/josegomezr/9bb195e816af3a8e2112).

**Comment by mogui** [comment]
@josegomezr this is still an open issues?

**Comment by josegomezr** [comment]
Long time no use this, i'll give it a look and report any errors.

**Comment by mogui** [comment]
closing this one for lack of ore info, we can reopen it if it needs
