### ISSUE TITLE
regression in handling of non-string values in dict passed to pyorient.orient.OrientDB.record_create()

### ISSUE THREAD

**Issue by lebedov** [mogui/pyorient#119]
As of 3c5ac78, passing a nested dict that specifies the class to use when creating the record via a '@classname' key and also contains a non-string value to `pyorient.orient.OrientDB.record_create()` raises an exception. For example, calling
```
import pyorient
client=pyorient.OrientDB('localhost', 2424)
client.db_open('temp', 'username', 'password')
client.record_create(9, {'@V': {'name': 'mux3', 'data': 3.2}})
```
where 9 is the ID associated with the V class causes the following:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lev/pyorient/pyorient/orient.py", line 439, in record_create
    .prepare(args).send().fetch_response()
  File "/home/lev/pyorient/pyorient/utils.py", line 49, in wrap_function
    return wrap(*args, **kwargs)
  File "/home/lev/pyorient/pyorient/utils.py", line 62, in wrap_function
    return wrap(*args, **kwargs)
  File "/home/lev/pyorient/pyorient/messages/records.py", line 75, in prepare
    record = self._record_content = OrientRecord( record )
  File "/home/lev/pyorient/pyorient/types.py", line 56, in __init__
    self.__o_storage[_key] = self.addslashes( _value )
  File "/home/lev/pyorient/pyorient/types.py", line 30, in addslashes
    if i in string:
TypeError: argument of type 'float' is not iterable
```
No exception is raised for the same code for earlier revisions of pyorient. 
Passing a dict that does not specify the class name (e.g., {'name': 'mux3', 'data': 3.2}) does not raise any exception in either case. 

I'm using pyorient with Python 2.7.10 and OrientDB 2.1.2.

**Comment by lebedov** [comment]
This problem seems to have gone away in 5b458ba (at least when I attempted to replicate it with Python 2.7.11 and OrientDB 2.1.8).
