### ISSUE TITLE
PyOrientConnectionException against 2.1.8 Server

### ISSUE THREAD

**Issue by lashex** [mogui/pyorient#164]
After successfully starting OrientDB v2.1.8
````
$ ./server.sh 
           .                                          
          .`        `                                 
          ,      `:.                                  
         `,`    ,:`                                   
         .,.   :,,                                    
         .,,  ,,,                                     
    .    .,.:::::  ````                                 :::::::::     :::::::::   
    ,`   .::,,,,::.,,,,,,`;;                      .:    ::::::::::    :::    :::  
    `,.  ::,,,,,,,:.,,.`  `                       .:    :::      :::  :::     ::: 
     ,,:,:,,,,,,,,::.   `        `         ``     .:    :::      :::  :::     ::: 
      ,,:.,,,,,,,,,: `::, ,,   ::,::`   : :,::`  ::::   :::      :::  :::    :::  
       ,:,,,,,,,,,,::,:   ,,  :.    :   ::    :   .:    :::      :::  :::::::     
        :,,,,,,,,,,:,::   ,,  :      :  :     :   .:    :::      :::  :::::::::   
  `     :,,,,,,,,,,:,::,  ,, .::::::::  :     :   .:    :::      :::  :::     ::: 
  `,...,,:,,,,,,,,,: .:,. ,, ,,         :     :   .:    :::      :::  :::     ::: 
    .,,,,::,,,,,,,:  `: , ,,  :     `   :     :   .:    :::      :::  :::     ::: 
      ...,::,,,,::.. `:  .,,  :,    :   :     :   .:    :::::::::::   :::     ::: 
           ,::::,,,. `:   ,,   :::::    :     :   .:    :::::::::     ::::::::::  
           ,,:` `,,.                                  
          ,,,    .,`                                  
         ,,.     `,                                          GRAPH DATABASE  
       ``        `.                                                          
                 ``                                          orientdb.com
                 `                                    

2016-01-07 21:09:08:189 INFO  OrientDB auto-config DISKCACHE=5,688MB (heap=455MB os=8,192MB disk=91,525MB) [orientechnologies]
2016-01-07 21:09:08:319 INFO  Loading configuration from: /Users/brett/dev/exo/orientdb-community-2.1.8/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2016-01-07 21:09:08:486 INFO  OrientDB Server v2.1.8 (build 2.1.x@r; 2015-12-17 11:51:38+0100) is starting up... [OServer]
2016-01-07 21:09:08:491 INFO  Databases directory: /Users/brett/dev/exo/orientdb-community-2.1.8/databases [OServer]
2016-01-07 21:09:08:521 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.32, socket=default) [OServerNetworkListener]
2016-01-07 21:09:08:527 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2016-01-07 21:09:08:540 INFO  Installing dynamic plugin 'studio-2.1.zip'... [OServerPluginManager]
2016-01-07 21:09:08:622 INFO  Installing GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
2016-01-07 21:09:08:623 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
2016-01-07 21:09:08:624 INFO  Installing Script interpreter. WARN: authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
2016-01-07 21:09:08:625 INFO  OrientDB Server v2.1.8 (build 2.1.x@r; 2015-12-17 11:51:38+0100) is active. [OServer]
````
and then installing the `pyorient` using this command: `pip install --pre --upgrade pyorient` to get version `pyorient==1.4.6a0`

This snippet of code:
````
import pyorient

# Trying OrientDB Graph DB since it seems to scale well
odb = pyorient.OrientDB("localhost", 2424)
odb_name = 'exo-db-mvp'
print('ODB Exists: {0}'.format(
    odb.db_exists(odb_name, pyorient.STORAGE_TYPE_MEMORY ))
)
odb_sid = odb.connect(odb_name, "admin", "fake-password")
````
...generates the following stack trace.
````
Traceback (most recent call last):
  File "app.py", line 75, in <module>
    odb.db_exists(odb_name, pyorient.STORAGE_TYPE_MEMORY ))
  File "/Users/brett/dev/exo/exo-start/venv/lib/python3.5/site-packages/pyorient/orient.py", line 343, in db_exists
    .prepare((name, type)).send().fetch_response()
  File "/Users/brett/dev/exo/exo-start/venv/lib/python3.5/site-packages/pyorient/messages/database.py", line 264, in fetch_response
    return super(DbExistsMessage, self).fetch_response()[0]
  File "/Users/brett/dev/exo/exo-start/venv/lib/python3.5/site-packages/pyorient/messages/base.py", line 256, in fetch_response
    self._decode_all()
  File "/Users/brett/dev/exo/exo-start/venv/lib/python3.5/site-packages/pyorient/messages/base.py", line 240, in _decode_all
    self._decode_header()
  File "/Users/brett/dev/exo/exo-start/venv/lib/python3.5/site-packages/pyorient/messages/base.py", line 186, in _decode_header
    serialized_exception = self._decode_field( FIELD_STRING )
  File "/Users/brett/dev/exo/exo-start/venv/lib/python3.5/site-packages/pyorient/messages/base.py", line 348, in _decode_field
    _value = self._orientSocket.read( _type['bytes'] )
  File "/Users/brett/dev/exo/exo-start/venv/lib/python3.5/site-packages/pyorient/orient.py", line 135, in read
    "Server seems to have went down", [])
pyorient.exceptions.PyOrientConnectionException: Server seems to have went down
````

**Comment by Ostico** [comment]
Server close the connection silently when a wrong password is provided. I will try if is possible to catch the exception in a better way.

**Comment by Ostico** [comment]
Hi @lashex ,
I tried your code and i've found an error.
You have to [open](https://github.com/mogui/pyorient#open-a-db) a database or [connect](https://github.com/mogui/pyorient#init-the-client) to a database before to issue commands like db_exists.

**Comment by lashex** [comment]
Thanks for the simple (and in hindsight a bit obvious) guidance.
