### ISSUE TITLE
RuntimeError: Attempt to use a broker name reserved by Graph. Could use a different name, or set the 'no_graph_broker' attribute to True for this element class.

### ISSUE THREAD

**Issue by decebal** [mogui/pyorient#224]
This error is so confusing, more so it's not consistent.
There are times when my ogm just works without modifying anything, but there are times when it fails with this generic error, which to me it means somehow it failed to set the `registry_plural` rather than using a reserved broker name. In the case it is a reserved broker name used, which one would that be ? 

My Traceback:
```
Traceback (most recent call last):
  File "loki.py", line 48, in <module>
    main()
  File "loki.py", line 23, in main
    app.run()
  File "/usr/local/lib/python3.6/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python3.6/site-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/loki/loki/controllers/base.py", line 125, in seed
    Data.feed_memorial_batch_sample_service()
  File "/loki/loki/faker/data.py", line 166, in feed_memorial_batch_sample_service
    'last_name': 'Duel'
  File "/loki/loki/services/memorial/memorialService.py", line 27, in save_memorial
    batch = cls.graph().batch()
  File "/loki/loki/services/memorial/memorialService.py", line 20, in graph
    graph.include(Node.registry)
  File "/usr/local/lib/python3.6/site-packages/pyorient/ogm/graph.py", line 108, in include
    self.init_broker_for_class(cls)
  File "/usr/local/lib/python3.6/site-packages/pyorient/ogm/graph.py", line 763, in init_broker_for_class
    'Attempt to use a broker name reserved by Graph. '
```

Here is a Node example: 
```
from pyorient.ogm import declarative

Node = declarative.declarative_node()

class Photo(Node):
    element_plural = 'photos'
    element_type = 'photo'

    caption = property.String()
    thumborId = property.String()
```

**Comment by decebal** [comment]
oh dear, so clearing the registry would prevent this error, embarrassing.
the unit tests are conclusive enough.
`graph.clear_registry()` before including everything else, solved my problem.
