### ISSUE TITLE
can't use db_drop after db_open

### ISSUE THREAD

**Issue by zeeshan2709** [mogui/pyorient#247]
@TropicalPenguin 

can be reproduced in the following way:

`import pyorient`
`client = pyorient.OrientDB("localhost", 2424)`
`client.db_open('test', 'root', 'rootpwd')`
`client.db_drop('test')`

```
Traceback (most recent call last):
  File "/src/user/tests/test_orientdb.py", line 29, in tearDown
    client.db_drop('test')
  File "/usr/local/lib/python2.7/site-packages/pyorient/orient.py", line 376, in db_drop
    .prepare((name, type)).send().fetch_response()
  File "/usr/local/lib/python2.7/site-packages/pyorient/messages/database.py", line 421, in fetch_response
    return super(DbDropMessage, self).fetch_response()
  File "/usr/local/lib/python2.7/site-packages/pyorient/messages/base.py", line 265, in fetch_response
    self._decode_all()
  File "/usr/local/lib/python2.7/site-packages/pyorient/messages/base.py", line 249, in _decode_all
    self._decode_header()
  File "/usr/local/lib/python2.7/site-packages/pyorient/messages/base.py", line 182, in _decode_header
    [ exception_message.decode( 'utf8' ) ]
PyOrientCommandException: java.lang.NullPointerException -
```

am i doing something wrong?

**Comment by Ostico** [comment]
Hi @zeeshan2709 ,

you can't drop a database after you opened it OrientDB do not permit that.

See the tests for the correct sequence:
https://github.com/mogui/pyorient/blob/master/tests/test_new_Iface.py#L55
