### ISSUE TITLE
PyOrient fails when selecting a Node that has no properties

### ISSUE THREAD

**Issue by josegomezr** [mogui/pyorient#80]
To mimic the error do run the following SQL:

```sql
CREATE CLASS Test EXTENDS V
CREATE VERTEX Test
```

Then in python:
```python
import pyorient
config = {
	'db_host': 'localhost',
	'db_port': 2424,
	'db_name': 'diggi-v1',
	'db_username': 'root',
	'db_password': 'veca3150'
}
client = pyorient.OrientDB(config['db_host'], config['db_port'])
client.db_open(config['db_name'], config['db_username'], config['db_password'])
client.query("SELECT FROM Test") # fails here.
```

It throws an `IndexError`, with this stacktrace:
```
Traceback (most recent call last):
  File "issue.py", line 15, in <module>
    client.query("SELECT FROM Po")
  File "/usr/local/lib/python2.7/dist-packages/pyorient/orient.py", line 256, in query
    .prepare(( QUERY_SYNC, ) + args).send().fetch_response()
  File "/usr/local/lib/python2.7/dist-packages/pyorient/messages/commands.py", line 149, in fetch_response
    return self._read_sync()
  File "/usr/local/lib/python2.7/dist-packages/pyorient/messages/commands.py", line 200, in _read_sync
    res.append( self._read_record() )
  File "/usr/local/lib/python2.7/dist-packages/pyorient/messages/base.py", line 419, in _read_record
    _res = ORecordDecoder(__res['content'].rstrip())
  File "/usr/local/lib/python2.7/dist-packages/pyorient/serialization.py", line 17, in __init__
    self.__decode( content )
  File "/usr/local/lib/python2.7/dist-packages/pyorient/serialization.py", line 36, in __decode
    chunk = self.parse_key(content)
  File "/usr/local/lib/python2.7/dist-packages/pyorient/serialization.py", line 104, in parse_key
    if content[ 0 ] == '"':
IndexError: string index out of range
```

I'm using Python 2.7 and OrientDB 2.0.9

**Comment by josegomezr** [comment]
The PR has been accepted so I'll close this issue.
