### ISSUE TITLE
cannot login without root user

### ISSUE THREAD

**Issue by el3ctron** [mogui/pyorient#88]
hi, i am trying to operate with other user diferent from root user (that is working good) but for security reasons i need to operate with new users

i create the user on the web interface

but when i change my configuration with the new user, pyorient says:

Traceback (most recent call last):
  File "./generar_respaldo", line 121, in <module>
    session_id = client.connect( usuario, n )
  File "/usr/local/lib/python2.7/dist-packages/pyorient/orient.py", line 208, in connect
    .prepare(args).send().fetch_response()
  File "/usr/local/lib/python2.7/dist-packages/pyorient/messages/connection.py", line 61, in fetch_response
    result = super( ConnectMessage, self ).fetch_response()
  File "/usr/local/lib/python2.7/dist-packages/pyorient/messages/base.py", line 204, in fetch_response
    self._decode_all()
  File "/usr/local/lib/python2.7/dist-packages/pyorient/messages/base.py", line 188, in _decode_all
    self._decode_header()
  File "/usr/local/lib/python2.7/dist-packages/pyorient/messages/base.py", line 170, in _decode_header
    raise PyOrientCommandException(cmd_exc, [])
pyorient.exceptions.PyOrientCommandException: Wrong user/password to [connect] to the remote OrientDB Server instance. Get the user/password from the config/orientdb-server-config.xml file - com.orientechnologies.orient.core.exception.OSecurityAccessException

i add to the file config/orientdb-server-config.xml (in the next line of root user and password configuration)
<user resources="*" password="userpswrd" name="newuser"/>

but nothing works

how can i operate with new users (with roles) in pyorient?

**Comment by el3ctron** [comment]
I restart the server and now appears:


Traceback (most recent call last):
  File "./generar_respaldo", line 124, in <module>
    lista=client.db_list()
  File "/usr/local/lib/python2.7/dist-packages/pyorient/orient.py", line 282, in db_list
    .prepare(args).send().fetch_response()
  File "/usr/local/lib/python2.7/dist-packages/pyorient/messages/database.py", line 552, in fetch_response
    __record = super( DbListMessage, self ).fetch_response()[0]
  File "/usr/local/lib/python2.7/dist-packages/pyorient/messages/base.py", line 204, in fetch_response
    self._decode_all()
  File "/usr/local/lib/python2.7/dist-packages/pyorient/messages/base.py", line 188, in _decode_all
    self._decode_header()
  File "/usr/local/lib/python2.7/dist-packages/pyorient/messages/base.py", line 170, in _decode_header
    raise PyOrientCommandException(cmd_exc, [])
pyorient.exceptions.PyOrientCommandException: Server user not authenticated. - com.orientechnologies.orient.core.exception.OSecurityAccessException

**Comment by Ostico** [comment]
Hi @el3ctron , you should provide me some line of code. 
I think you not set the right permissions ( in the orient config ) that you are using in the code.
